title: Blog
description: My blog
author: Batuhan Aydın
github: https://github.com/batuhan-aydin
about: I'm Pa Software Engineer interested in backend development. I've made quite a few web apps on differen programming languages and frameworks.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/ArcTrooperMen"
    - icon: fa-twitter
      link: "https://twitter.com/droidarc"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/batuhan-ayd%C4%B1n-40a311117/"
    - icon: fa-github
      link: "https://github.com/batuhan-aydin"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
